
# set 256 color
set -g default-terminal "tmux-256color"
# tell Tmux that outside terminal supports true color
set -ga terminal-overrides ",xterm-256color*:Tc"

# set -g default-terminal "screen-256color"

# Основной префикс
set -g prefix C-a

set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none
# Сортировка по имени
bind s choose-tree -sZ -O name

# Изменение индексов
set -g base-index 1
setw -g pane-base-index 1

# Переназначение клавиш
unbind %
bind v split-window -h

unbind '"'
bind h split-window -v

unbind r
bind r source-file ~/.tmux.conf

bind -r M-Down resize-pane -D 5
bind -r M-Up resize-pane -U 5
bind -r M-Right resize-pane -R 5
bind -r M-Left resize-pane -L 5

# bind -r m resize-pane -Z

bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D
set -g mouse on

set-window-option -g mode-keys vi
set-option -g status-position top
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection

unbind -T copy-mode-vi MouseDragEnd1Pane
bind -n C-Tab next-window
# bind -n C-Shift-Tab previous-window

set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"
set -g status-right-length 200
set -g status-left-length 100
set -g status-left ""
set -ogq @catppuccin_pane_status_enabled "yes" # set to "yes" to enable
set -g  status-right "#{E:@catppuccin_status_directory}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -ag status-right '#{E:@catppuccin_status_date_time}'

## Window global/default configuration
# set -g @catppuccin_window_default_text " #{window_name}"
# set -g @catppuccin_window_default_text " AA #{b:pane_current_path}"
set -g @catppuccin_window_text ' #{b:pane_current_path}'
set -g @catppuccin_window_default_fill "all"

set -g @catppuccin_window_status "icon"
set -g @catppuccin_window_number_position "left"
## Window current configuration
set -g @catppuccin_window_current_text " #{b:pane_current_path}"
set -g @catppuccin_window_current_fill "all"
set -g @catppuccin_window_current_middle_separator " "

set -g @catppuccin_date_time_text ' %H:%M %d.%m'
set -g @catppuccin_window_left_separator ""
set -g @catppuccin_window_right_separator ""
set -g @catppuccin_window_number_position "left"
set -g @catppuccin_window_middle_separator " | "
# set -g @catppuccin_window_default_fill "none"
# set -ogq @catppuccin_pane_default_text "##{b:pane_current_path}"
# set -ogq @catppuccin_pane_default_fill "number"

set-option -g status-interval 5
set-option -g automatic-rename off
# set-option -g automatic-rename-format "#{b:pane_current_path}"
set -g @resurrect-dir '$HOME/.tmux_resurrect'

set -g @resurrect-capture-pane-contents 'on'
set -g @continuum-restore 'on'
# set -g @continuum-boot 'on'
# set -g @continuum-boot-options 'wezterm,fullscreen'

# Плагины
set -ogq @plugin 'catppuccin/tmux#v2.1.0'
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-sessionist'
set -g @plugin 'tmux-plugins/tmux-continuum'
run '~/.tmux/plugins/tpm/tpm'
run-shell ~/.tmux/plugins/tmux-resurrect/resurrect.tmux
run ~/.tmux/plugins/tmux/catppuccin.tmux
# run '~/.tmux/plugins/tmux/catppuccin.tmux'

# Старт менеджера плагинов
#
# set -ga pane-active-border-style fg=red,bold
# set -ga pane-border-style fg=green

